// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function First() {
  return window['go']['extension']['index']['First']();
}

export function Last() {
  return window['go']['extension']['index']['Last']();
}

export function Next() {
  return window['go']['extension']['index']['Next']();
}

export function Prev() {
  return window['go']['extension']['index']['Prev']();
}

export function Reload() {
  return window['go']['extension']['index']['Reload']();
}

export function State() {
  return window['go']['extension']['index']['State']();
}

export function Upload(arg1) {
  return window['go']['extension']['index']['Upload'](arg1);
}
