// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {extension} from '../models';

export function First():Promise<void>;

export function Last():Promise<void>;

export function Next():Promise<void>;

export function Prev():Promise<void>;

export function Reload():Promise<void>;

export function State():Promise<extension.State>;

export function Upload(arg1:string):Promise<void>;
