// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class State {
    /**
     * Creates a new State instance.
     * @param {Partial<State>} [$$source = {}] - The source object to create the State.
     */
    constructor($$source = {}) {
        if (!("Links" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["Links"] = [];
        }
        if (!("Player" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Player"] = 0;
        }
        if (!("Current" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Current"] = "";
        }
        if (!("CurrentDomain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CurrentDomain"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {State}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Links" in $$parsedSource) {
            $$parsedSource["Links"] = $$createField0_0($$parsedSource["Links"]);
        }
        return new State(/** @type {Partial<State>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
