// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Action, Ch = ext.Startup()
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function First() {
    return $Call.ByID(3694557431);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Last() {
    return $Call.ByID(3838857859);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Next() {
    return $Call.ByID(133647258);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Prev() {
    return $Call.ByID(714663502);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Reload() {
    return $Call.ByID(104444618);
}

/**
 * @returns {$CancellablePromise<$models.State>}
 */
export function State() {
    return $Call.ByID(1374473812).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} str
 * @returns {$CancellablePromise<void>}
 */
export function Upload(str) {
    return $Call.ByID(494939862, str);
}

// Private type creation functions
const $$createType0 = $models.State.createFrom;
